const { BaseModel } = require('component-model');
const { Identity } = require('./identity');

const { resolveUserForContext, userIdentityIdForContext } = require('../shared-helpers/access');
const ModelSubmissionComment = require('./submission-comment');
const SubmissionComment = ModelSubmissionComment.model;

class Comment extends BaseModel {

    static get tableName() {
        return 'comment';
    }

    static get schema() {
        return {
            type: 'object',
            properties: {
                author_id: { type: ['string', 'null'], format: 'uuid'},
                comment_body: { type: ['string', 'null'] },
            }
        };
    }

    $beforeInsert() {
      // id is auto-generated by backend
      this.created = new Date().toISOString()
      this.updated = this.created
    }

    static get relationMappings() {

        return {
            author: {
                relation: BaseModel.BelongsToOneRelation,
                modelClass: Identity,
                join: {
                    from: `${this.tableName}.authorId`,
                    to: `${Identity.tableName}.id`
                }
            }
        };
    }

    // Required for relation resolution
    static get relationFieldNames() {
        return ['author'];
    }

    // Required for relation resolution
    static get belongsToOneRelationFields() {
        return [
            {
                field: {
                    field: 'author',
                    type: 'Identity',
                    joinField: 'authorId',
                    model: Identity
                },
                join: 'authorId'
            }
        ];
    }

    static get defaultEager () {
        return 'author';
    }

}

exports.model = exports.Comment = Comment;


exports.resolvers = {

    Mutation: {

        commentOnSubmission: async function(_, {input:{submission_id, comment_body}}, context) {
            const author_id = userIdentityIdForContext(context);
            const currentDateTime = new Date().toISOString();
            const comment = new Comment({
                created: currentDateTime,
                updated: currentDateTime,
                author_id: author_id,
                comment_body: comment_body
            });
            await comment.save();
            const submission_comment = new SubmissionComment({
                submission_id: submission_id,
                comment_id: comment.id
            });
            await submission_comment.save();
            return comment;
        }
    }

};
